/*
 *
 * Copyright 2025-2026 The FairScan authors
 * Copyright 2026 Ruben Matias
 *
 * Modified by Ruben Matias in 2026.
 * This file is part of the Nopalito Scan fork.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <https://www.gnu.org/licenses/>.
 *
 */

package nopalito.app.ui.screens.cloud.data

import android.content.Context
import android.util.Log
import nopalito.app.ui.screens.cloud.model.QrScan
import nopalito.app.ui.screens.qr.QrDetected
import nopalito.app.ui.screens.qr.encodeQrType
import java.io.File

private const val TAG = "CloudScanUploader"

/**
 * Pushes a freshly scanned QR/barcode to the cloud history (POST /api/scans),
 * including the captured thumbnail, when the user has an active session.
 *
 * Best-effort and non-blocking: a failed upload only logs a warning and never
 * interrupts the local scan save.
 * ponytail: no offline queue/retry — add a WorkManager retry if scans must
 *           survive periods without connectivity.
 */
class CloudScanUploader(context: Context) {

    private val repository = CloudRepository(context)

    /**
     * Whether valid session tokens exist. Preferred over the in-memory
     * [CloudSessionManager.state], which can lag (Checking/Error) even when the
     * user is actually authenticated. If the tokens are invalid the API call
     * itself will return 401 and the push is simply reported as failed.
     */
    fun hasSession(): Boolean = repository.hasSession()

    suspend fun upload(detected: QrDetected, imagePath: String?) {
        if (!hasSession()) return
        val image = imagePath?.let { File(it).takeIf { f -> f.exists() } }
        val scan = QrScanUpload(
            content = detected.content,
            type = typeName(detected.type),
            typeData = encodeQrType(detected.type),
            format = detected.format,
            scannedAt = System.currentTimeMillis(),
        )
        repository.pushScan(scan, image)
            .onSuccess { Log.d(TAG, "Scan pushed to cloud") }
            .onFailure { Log.w(TAG, "Cloud scan upload failed (${it.javaClass.simpleName})") }
    }

    /**
     * Pushes a QR generated by the QR generator to the cloud history.
     * @return the server result (Success with the created scan, or Failure with
     *         the underlying error message so the caller can surface it).
     */
    suspend fun uploadGenerated(
        content: String,
        type: String,
        typeData: String?,
        format: String?,
        design: String?,
        imagePath: String?,
    ): Result<QrScan?> {
        val image = imagePath?.let { File(it).takeIf { f -> f.exists() } }
        val scan = QrScanUpload(
            content = content,
            type = type,
            typeData = typeData,
            format = format,
            design = design,
            scannedAt = System.currentTimeMillis(),
        )
        return repository.pushScan(scan, image)
            .onSuccess { Log.d(TAG, "Generated QR pushed to cloud") }
            .onFailure { Log.w(TAG, "Cloud generated-QR upload failed (${it.javaClass.simpleName})") }
    }

    private fun typeName(type: QrDetected.Type): String = when (type) {
        is QrDetected.Type.Text -> "text"
        is QrDetected.Type.Url -> "url"
        is QrDetected.Type.Wifi -> "wifi"
        is QrDetected.Type.Email -> "email"
        is QrDetected.Type.Phone -> "phone"
        is QrDetected.Type.Sms -> "sms"
        is QrDetected.Type.Geo -> "geo"
    }
}
