/*
 *
 * Copyright 2025-2026 The FairScan authors
 * Copyright 2026 Ruben Matias
 *
 * Modified by Ruben Matias in 2026.
 * This file is part of the Nopalito Scan fork.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <https://www.gnu.org/licenses/>.
 *
 */

package nopalito.app.ui.screens.tools.shared

import android.graphics.Bitmap
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Info
import androidx.compose.material.icons.filled.Lock
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import nopalito.app.R

/** Title + hint of the file preview, shown in the scrollable content. */
@Composable
fun FilePreviewInfo(fileType: PreviewFileType) {
    Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
        Text(
            text = stringResource(R.string.tools_preview_title),
            style = MaterialTheme.typography.labelLarge,
            fontWeight = FontWeight.SemiBold,
            color = MaterialTheme.colorScheme.onSurface,
        )
        Text(
            text = stringResource(R.string.tools_preview_hint),
            style = MaterialTheme.typography.bodySmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
        )
        if (fileType == PreviewFileType.WORD) {
            Text(
                text = stringResource(R.string.tools_wifi_requires_internet),
                style = MaterialTheme.typography.bodySmall,
                color = MaterialTheme.colorScheme.onSurfaceVariant,
            )
        }
    }
}

/** Shown while a Word/office preview is being generated by the backend. */
@Composable
fun FilePreviewLoading() {
    Surface(
        shape = RoundedCornerShape(12.dp),
        color = MaterialTheme.colorScheme.primaryContainer,
        modifier = Modifier.fillMaxWidth(),
    ) {
        Row(
            verticalAlignment = Alignment.CenterVertically,
            modifier = Modifier.padding(14.dp),
        ) {
            CircularProgressIndicator(modifier = Modifier.size(22.dp), strokeWidth = 2.dp)
            Spacer(Modifier.width(10.dp))
            Text(
                text = stringResource(R.string.tools_preview_loading),
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onPrimaryContainer,
            )
        }
    }
}

/** Shown when the preview could not be generated (the tool still works). */
@Composable
fun FilePreviewFailed(protected: Boolean = false) {
    Surface(
        shape = RoundedCornerShape(12.dp),
        color = if (protected) {
            MaterialTheme.colorScheme.errorContainer
        } else {
            MaterialTheme.colorScheme.surfaceContainerLow
        },
        modifier = Modifier.fillMaxWidth(),
    ) {
        Row(
            verticalAlignment = Alignment.CenterVertically,
            modifier = Modifier.padding(14.dp),
        ) {
            Icon(
                imageVector = if (protected) Icons.Default.Lock else Icons.Default.Info,
                contentDescription = null,
                tint = if (protected) {
                    MaterialTheme.colorScheme.onErrorContainer
                } else {
                    MaterialTheme.colorScheme.onSurfaceVariant
                },
                modifier = Modifier.size(20.dp),
            )
            Spacer(Modifier.width(10.dp))
            Text(
                text = stringResource(
                    if (protected) R.string.tools_preview_protected
                    else R.string.tools_preview_unavailable
                ),
                style = MaterialTheme.typography.bodyMedium,
                color = if (protected) {
                    MaterialTheme.colorScheme.onErrorContainer
                } else {
                    MaterialTheme.colorScheme.onSurfaceVariant
                },
            )
        }
    }
}

/**
 * Horizontal strip of thumbnails (read-only, left to right). PDFs and
 * Word/office documents (converted to a temporary PDF by the backend) show
 * one thumbnail per page, images a single thumbnail.
 */
@Composable
fun FilePreviewStrip(
    fileType: PreviewFileType,
    pageCount: Int,
    render: suspend (pageIndex: Int, targetWidthPx: Int) -> Bitmap?,
    modifier: Modifier = Modifier,
) {
    LazyRow(
        contentPadding = PaddingValues(horizontal = 16.dp, vertical = 6.dp),
        horizontalArrangement = Arrangement.spacedBy(8.dp),
        verticalAlignment = Alignment.CenterVertically,
        modifier = modifier.fillMaxWidth(),
    ) {
        itemsIndexed(
            (1..pageCount).toList(),
            key = { _, pageNumber -> pageNumber },
        ) { index, pageNumber ->
            FilePreviewItem(
                fileType = fileType,
                pageNumber = pageNumber,
                position = index,
                render = render,
            )
        }
    }
}

/**
 * Batch preview: one read-only thumbnail strip per picked file, shown in the
 * scrollable content (multiple strips cannot be pinned at the bottom).
 * Photos share a single strip (a row per photo would stretch the screen).
 */
@Composable
fun FilePreviewBatchSection(
    fileType: PreviewFileType,
    previews: List<PreviewFileState>,
    renderBatch: suspend (uriKey: String, pageIndex: Int, targetWidthPx: Int) -> Bitmap?,
) {
    Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
        FilePreviewInfo(fileType)
        if (fileType == PreviewFileType.IMAGE) {
            LazyRow(
                contentPadding = PaddingValues(horizontal = 16.dp, vertical = 6.dp),
                horizontalArrangement = Arrangement.spacedBy(8.dp),
                verticalAlignment = Alignment.CenterVertically,
                modifier = Modifier.fillMaxWidth(),
            ) {
                itemsIndexed(previews, key = { _, preview -> preview.uriKey }) { _, preview ->
                    BatchImagePreviewItem(preview = preview, renderBatch = renderBatch)
                }
            }
        } else {
            previews.forEach { preview ->
                Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {
                    Text(
                        text = preview.fileName,
                        style = MaterialTheme.typography.labelMedium,
                        fontWeight = FontWeight.SemiBold,
                        maxLines = 1,
                        overflow = TextOverflow.Ellipsis,
                    )
                    when {
                        preview.isLoading -> FilePreviewLoading()
                        preview.failed -> FilePreviewFailed(protected = preview.protected)
                        else -> FilePreviewStrip(
                            fileType = fileType,
                            pageCount = preview.pageCount,
                            render = { pageIndex, targetWidth ->
                                renderBatch(preview.uriKey, pageIndex, targetWidth)
                            },
                        )
                    }
                }
            }
        }
    }
}

/** One thumbnail: page image + page number badge (PDF/Word) or plain image. */
@Composable
private fun FilePreviewItem(
    fileType: PreviewFileType,
    pageNumber: Int,
    position: Int,
    render: suspend (pageIndex: Int, targetWidthPx: Int) -> Bitmap?,
) {
    var bitmap by remember(pageNumber) { mutableStateOf<Bitmap?>(null) }
    var failed by remember(pageNumber) { mutableStateOf(false) }

    BoxWithConstraints(
        modifier = Modifier.width(PREVIEW_THUMBNAIL_WIDTH_DP),
        contentAlignment = Alignment.Center,
    ) {
        val targetWidth = constraints.maxWidth.coerceAtLeast(60)

        LaunchedEffect(pageNumber, targetWidth) {
            val rendered = render(pageNumber - 1, targetWidth)
            if (rendered == null) {
                failed = true
            } else {
                bitmap?.recycle()
                bitmap = rendered
            }
        }
        DisposableEffect(pageNumber) {
            onDispose { bitmap?.recycle() }
        }

        Column(horizontalAlignment = Alignment.CenterHorizontally) {
            Card(
                elevation = CardDefaults.cardElevation(defaultElevation = 2.dp),
                shape = RoundedCornerShape(6.dp),
                border = BorderStroke(1.dp, Color.LightGray),
            ) {
                Box(
                    modifier = Modifier
                        .width(PREVIEW_THUMBNAIL_WIDTH_DP)
                        .height(PREVIEW_THUMBNAIL_HEIGHT_DP),
                    contentAlignment = Alignment.Center,
                ) {
                    val bmp = bitmap
                    when {
                        bmp != null -> Image(
                            bitmap = bmp.asImageBitmap(),
                            contentDescription = null,
                            contentScale = ContentScale.Fit,
                            modifier = Modifier.fillMaxSize(),
                        )

                        failed -> Text(
                            text = stringResource(R.string.ror_preview_failed),
                            style = MaterialTheme.typography.labelSmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                            textAlign = TextAlign.Center,
                            modifier = Modifier.padding(4.dp),
                        )

                        else -> CircularProgressIndicator(
                            modifier = Modifier.size(20.dp),
                            strokeWidth = 2.dp,
                        )
                    }
                    if (fileType != PreviewFileType.IMAGE) {
                        Surface(
                            shape = RoundedCornerShape(4.dp),
                            color = Color.Black.copy(alpha = 0.5f),
                            contentColor = Color.White,
                            modifier = Modifier
                                .align(Alignment.BottomCenter)
                                .padding(4.dp),
                        ) {
                            Text(
                                text = "$pageNumber",
                                style = MaterialTheme.typography.labelSmall,
                                fontWeight = FontWeight.SemiBold,
                                fontSize = 10.sp,
                                modifier = Modifier.padding(horizontal = 6.dp, vertical = 1.dp),
                            )
                        }
                    }
                }
            }
            if (fileType != PreviewFileType.IMAGE) {
                Spacer(Modifier.height(4.dp))
                Text(
                    text = stringResource(R.string.ror_position, position + 1),
                    style = MaterialTheme.typography.labelSmall,
                    fontSize = 10.sp,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
            }
        }
    }
}

/** One photo of the batch preview strip: thumbnail + file name label. */
@Composable
private fun BatchImagePreviewItem(
    preview: PreviewFileState,
    renderBatch: suspend (uriKey: String, pageIndex: Int, targetWidthPx: Int) -> Bitmap?,
) {
    var bitmap by remember(preview.uriKey) { mutableStateOf<Bitmap?>(null) }
    var failed by remember(preview.uriKey) { mutableStateOf(false) }

    BoxWithConstraints(
        modifier = Modifier.width(PREVIEW_THUMBNAIL_WIDTH_DP),
        contentAlignment = Alignment.Center,
    ) {
        val targetWidth = constraints.maxWidth.coerceAtLeast(60)

        LaunchedEffect(preview.uriKey, preview.isLoading, preview.failed, targetWidth) {
            if (preview.isLoading || preview.failed) return@LaunchedEffect
            val rendered = renderBatch(preview.uriKey, 0, targetWidth)
            if (rendered == null) {
                failed = true
            } else {
                bitmap?.recycle()
                bitmap = rendered
            }
        }
        DisposableEffect(preview.uriKey) {
            onDispose { bitmap?.recycle() }
        }

        Column(horizontalAlignment = Alignment.CenterHorizontally) {
            Card(
                elevation = CardDefaults.cardElevation(defaultElevation = 2.dp),
                shape = RoundedCornerShape(6.dp),
                border = BorderStroke(1.dp, Color.LightGray),
            ) {
                Box(
                    modifier = Modifier
                        .width(PREVIEW_THUMBNAIL_WIDTH_DP)
                        .height(PREVIEW_THUMBNAIL_HEIGHT_DP),
                    contentAlignment = Alignment.Center,
                ) {
                    val bmp = bitmap
                    when {
                        preview.isLoading -> CircularProgressIndicator(
                            modifier = Modifier.size(20.dp),
                            strokeWidth = 2.dp,
                        )

                        preview.failed -> Text(
                            text = stringResource(R.string.ror_preview_failed),
                            style = MaterialTheme.typography.labelSmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                            textAlign = TextAlign.Center,
                            modifier = Modifier.padding(4.dp),
                        )

                        bmp != null -> Image(
                            bitmap = bmp.asImageBitmap(),
                            contentDescription = null,
                            contentScale = ContentScale.Fit,
                            modifier = Modifier.fillMaxSize(),
                        )

                        failed -> Text(
                            text = stringResource(R.string.ror_preview_failed),
                            style = MaterialTheme.typography.labelSmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                            textAlign = TextAlign.Center,
                            modifier = Modifier.padding(4.dp),
                        )

                        else -> CircularProgressIndicator(
                            modifier = Modifier.size(20.dp),
                            strokeWidth = 2.dp,
                        )
                    }
                }
            }
            Spacer(Modifier.height(4.dp))
            Text(
                text = preview.fileName,
                style = MaterialTheme.typography.labelSmall,
                fontSize = 10.sp,
                maxLines = 1,
                overflow = TextOverflow.Ellipsis,
                modifier = Modifier.width(PREVIEW_THUMBNAIL_WIDTH_DP),
            )
        }
    }
}

private val PREVIEW_THUMBNAIL_WIDTH_DP = 110.dp
private val PREVIEW_THUMBNAIL_HEIGHT_DP = 150.dp
